print("My Name is Sudhanshu Yadav")
print("I am learning python automation")
print("Python was developed by Guido van Rossum.",end="")
print("Python is a Programming language")
print(1)
print(2)
print(3)
print(4,end="")
print(5, end="")
print(6)
print(7 , end=" ")
print(8 , end=" ")
print(9)