a = 6.8
print(type(a))
print(a)
b = int(5)
print(type(b))
print(b)
c = "4"
print(type(c))
print(c)
d = int("8")
print(type(d))
print(d * 2)
e = "5"
print(type(e))
print(e + "2")
f = float(27)
print(type(f))
print(f)
g = float("143")
print(type(g))
print(g)
h = str(12)
print(type(h))
print(h + " is a number string")
i = str(13)
print(type(i))
print(i + " is a floating string")
j = "132"
print(type(j))
print(j+1)
k = int("Sudhanshu")
print(type(k))
print(k+1)