print(bool(0))                                      #Will return FALSE
print(bool(1))                                      #Will return TRUE
print(bool(1912))                                   #Will return TRUE
print(bool(""))                                     #Will Return FALSE
print(bool("Sudhanshu"))                            #Will Return TRUE
print(bool([5,8,78,90]))                            #Will Return TRUE
print(bool([]))                                     #Will Return FALSE
print(bool((5,8,78,90)))                            #Will Return TRUE
print(bool(()))                                     #Will Return FALSE